### ISSUE TITLE
How to run it in Mac OS?

### ISSUE THREAD

**Issue by MetroBear** [ZyqGitHub1/h-player-v2#12]
How to run it in Mac OS?

**Comment by ZyqGitHub1** [comment]
This project uses electron, electron to build cross-platform desktop applications. But currently I don't have a Mac OS development environment to build this application. I will find a way to solve this problem, including the following two points.
1. Improve the build documentation so that developers can build their own
2. Try to find the Mac OS development environment

-----

本项目使用electron，electron能构建跨平台的桌面应用。但是当前我没有可以构建这个应用的Mac OS开发环境。我会想办法解决这个问题，包括以下两点
1. 完善构建文档，方便开发者自己构建
2. 尝试寻找Mac OS开发环境

**Comment by thuxx** [comment]
Actually this project can directly run on MacOS after building.
Thanks.

**Comment by sdy0803** [comment]
> Actually this project can directly run on MacOS after building.
> Thanks.

could you talk a little more about how to build this project on MacOS? Thx

**Comment by pkwenda** [comment]
electron 默认是按自己平台架构打包，如果后面加 --linux 或 --win 或 --mac 就可以打成相应平台的包，你试试 我之前用的也是 electron-vue 就是这么打的包

**Comment by ZyqGitHub1** [comment]
The 0.8.0 version provides a .dmg file that can be installed on the osx system.

------

0.8.0版本提供了.dmg文件，可以在osx系统安装
