### ISSUE TITLE
支持解析多集播放列表

### ISSUE THREAD

**Issue by anglesgirl** [ZyqGitHub1/h-player-v2#23]
如果加载的资源是电视剧
那么只能播放第一集 其他的集数没有办法显示也点不到播放
这个能不能优先解决一下

**Comment by anglesgirl** [comment]
这是苹果cms的api提供的呀
苹果cms有说明文档

**Comment by dpk3** [comment]
我用的海洋的也可以采集下来，电视剧的问题我也发现了 没有办法选集是很尴尬 有的播最后一集 有的播第一集

**Comment by ZyqGitHub1** [comment]
The 0.5.0 release releases the software's UI, and the internal parsing function adds initial support for multi-set video. Multi-set video parsing may need to be further improved due to differences in api details between different video sources. #25 

-------

0.5.0版本release更新了软件的UI，内部解析函数添加了初步的对多集视频的支持。由于不同视频源的api细节差异，多集视频解析功能可能需要进一步完善。#25
