### ISSUE TITLE
搜索功能无法使用

### ISSUE THREAD

**Issue by Qiuye666** [ZyqGitHub1/h-player-v2#29]
如题，搜索功能无法使用，输入资源名称后，按回车键毫无反应，该怎么解决？

**Comment by ZyqGitHub1** [comment]
Please describe the specific website where the search function is not available. The search function of some resource collection networks cannot be used because its api search function is abnormal. For example, ok resource network. If anyone finds out how to call the search API of ok resource network, please let me know, thank you very much.

------

请说明搜索功能无法使用的具体网站。部分资源采集网的搜索功能无法使用，是因为其api搜索功能表现异常。例如ok资源网。如果有人发现如何调用ok资源网的搜索api，请告诉我，非常感谢。

**Comment by anglesgirl** [comment]
所有的资源站都是两种资源结构，xml跟json，其中xml也就有新旧两个版本，苹果cms官方有说明，你可以把苹果cms的后台采集源码看一次，参考api说明折腾一下
为什么会以苹果cms为主要呢，还不是苹果cms站长太多，资源站为了最大的兼容，都会选最流行的程序，然后其他程序为了方便资源站对接，也放弃了自己的模式，统一采用苹果 cms的api结构
关于ok资源，你是用的json还是xml
http://cj.okzy.tv/inc/apickm3u8s.php他们的api应该是这个

搜索参数应该是 http://cj.okzy.tv/inc/apickm3u8s.php?wd=鬼吹灯
