### ISSUE TITLE
怎么在Linux上部署，麻烦给个简要的教程

### ISSUE THREAD

**Issue by LiMingHuaDuo** [ZyqGitHub1/h-player-v2#34]
想在自用的小服务器上搭一个

**Comment by ZyqGitHub1** [comment]
This project is a desktop application packaged with electron, not a server. If you want to package an application for a Linux desktop environment, you need to install nodejs and yarn, then clone the project to the local, run yarn install in the project local directory. Install dependencies, then run the yarn electron:build package application. Please refer to [quasar](https://quasar.dev/quasar-cli/developing-electron-apps) for details. If you want to build a server, sorry, this is not a feature included in the current version of this project.

------

这个项目是一个用electron打包的桌面应用程序，而不是一个服务器，如果你想打包一个linux桌面环境使用的应用，那么需要安装nodejs和yarn，然后将项目clone到本地，在项目本地目录运行yarn install安装依赖，之后运行yarn electron:build打包应用。具体请参考[quasar](https://quasar.dev/quasar-cli/developing-electron-apps)。如果你想搭建一个服务器，抱歉，这不是本项目当前版本包含的功能

**Comment by weiyouwozuiku** [comment]
能提供一下打包好的linux的应用么？我的yarn有些问题。

**Comment by LiMingHuaDuo** [comment]
> 这个项目是一个包含电子的桌面应用程序，而不是服务器。如果要为Linux桌面环境打包应用程序，则需要安装nodejs和yarn，然后将项目克隆到本地，在项目本地目录中运行yarn install。安装依赖项，然后运行yarn electron：build包应用程序。有关详细信息，请参阅[类星体](https://quasar.dev/quasar-cli/developing-electron-apps)。如果您想构建服务器，抱歉，这不是此项目当前版本中包含的功能。
> 
> 这个项目是一个用电子打包的桌面应用程序，而不是一个服务器，如果你想打包一个linux桌面环境使用的应用，那么需要安装nodejs和纱，然后将项目克隆到本地，在项目本地目录运行纱线安装安装依赖，之后运行yarn electron：build打包应用。具体请参考[quasar](https://quasar.dev/quasar-cli/developing-electron-apps)。如果你想搭建一个服务器，抱歉，这不是本项目当前版本包含的功能

thanks，I know what software this is, and I saw it correctly.

**Comment by ZyqGitHub1** [comment]
Version 0.8.0 provides an .AppImage file that can be run on a Linux system.

## NOTE

Since the electron 5 or later version introduced the sandbox mechanism. So use appimage in linux system, if there is any problem related to sandbox, please add `--no-sandbox` parameter to run.

------

0.8.0版本提供了.AppImage文件，可以在linux系统运行。

## 注意

由于electron 5以上版本引入了sandbox机制。所以在linux系统下使用appimage如出现sandbox相关问题请添加 `--no-sandbox`参数运行
